### ISSUE TITLE
[BUG] Deleting Item outputs error 401

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/tpos#53] opened 2023-12-07 10:22 UTC
### **Issue:**
Use new TPoS and deleting and item i added before leads in an error and item is still existing. Also after hard refresh item still existing.

![Delete Item Error](https://github.com/lnbits/tpos/assets/106493492/5f841ba6-3f94-4333-904b-232e2fd0957b)

The Button "DELETE ALL" is working fine.

### **Reproduce:**
1) Use TPoS with System requirements provided below
2) Add item
3) Try to delete Item

System:
LNBits 0.11.2
TPoS 0.5.1

**Comment by prusnak** [comment] 2023-12-07 10:25
Duplicate of #48 (already fixed)

**Closed** 2023-12-07 10:26 UTC

**Comment by DoktorShift** [comment] 2023-12-07 10:30
sry for the noise! Just dont saw it...
