### ISSUE TITLE
[Feature Request] Add On-Chain possibilty

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/tpos#85] opened 2024-05-07 21:51 UTC
Add the possibility to accept on-chain payments as well as ln payments.

Frontend could work like an extra option with a slide button in editing area "enable on-chain" and a text field "Enter on-chain address here". 

The Backend could be realized trough invoice extension or satspay extension.

**Comment by prusnak** [comment] 2024-05-07 22:25
Duplicate of https://github.com/lnbits/tpos/issues/25

**Closed** 2024-05-07 22:25 UTC
